version: '3.6'

services:

  zookeeper:
    container_name: zookeeper
    image: zookeeper:latest
    restart: on-failure
    volumes:
      - "./zookeeper/data:/data"
      - "./zookeeper/logs:/datalog"
    ports:
      - "2181:2181"

  kafka1:
    container_name: kafka1
    image: wurstmeister/kafka:latest
    restart: on-failure
    ports:
      - 9092
    links:
      - zookeeper
    environment:
      KAFKA_LOG_DIRS: /kafka
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CREATE_TOPICS: "velib:12:3,bug:12.3"
      KAFKA_LOG_RETENTION_BYTES: 300000000
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_HOURS: 72
    volumes:
      - "./kfcluster/kafka1:/kafka"

  kafka2:
    container_name: kafka2
    image: wurstmeister/kafka:latest
    restart: on-failure
    ports:
      - 9093
    links:
      - zookeeper
    environment:
      KAFKA_LOG_DIRS: /kafka
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:29093,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka2:29093,PLAINTEXT_HOST://localhost:9093
      KAFKA_LOG_RETENTION_BYTES: 300000000
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_HOURS: 72
    volumes:
      - "./kfcluster/kafka2:/kafka"

  kafka3:
    container_name: kafka3
    image: wurstmeister/kafka:latest
    restart: on-failure
    ports:
      - 9094
    links:
      - zookeeper
    environment:
      KAFKA_LOG_DIRS: /kafka
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:29094,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka3:29094,PLAINTEXT_HOST://localhost:9094
      KAFKA_LOG_RETENTION_BYTES: 300000000
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_HOURS: 72
    volumes:
      - "./kfcluster/kafka3:/kafka"

  producervelib:
    container_name: producervelib
    image: producervelib:latest
    restart: on-failure
    depends_on:
      - kafka1
      - kafka2
      - kafka3

  consumer:
    container_name: consumer
    image: consumer:latest
    restart: on-failure
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    volumes:
     - ./data:/usr/src/app/data

  consumerbug:
    container_name: consumerbug
    image: consumerbug:latest
    restart: on-failure
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    volumes:
     - ./data:/usr/src/app/data


  api:
    container_name: api
    image: api:latest
    restart: on-failure
    ports:
     - "7000:7000"
    volumes:
     - ./data:/usr/src/app/data:ro